# Generated by Django 4.2 on 2023-04-11 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=100)),
                ('data_nasc', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=20)),
                ('estado_civil', models.CharField(max_length=100)),
                ('paratleta', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('telefone_residencial', models.CharField(max_length=100)),
                ('telefone_comercial', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('dependente_01', models.CharField(max_length=100)),
                ('dependente_02', models.CharField(max_length=100)),
                ('dependente_03', models.CharField(max_length=100)),
                ('dependente_04', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('data_emissao', models.CharField(max_length=100)),
                ('passaporte', models.CharField(max_length=100)),
                ('validade_passaporte', models.CharField(max_length=100)),
                ('cr', models.CharField(max_length=100)),
                ('validade_cr', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=100)),
            ],
        ),
    ]
