# Generated by Django 4.1.7 on 2023-04-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('naturalidade', models.CharField(max_length=100)),
                ('data_nasc', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
                ('paratleta', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('telefone_residencial', models.CharField(blank=True, max_length=100)),
                ('telefone_comercial', models.CharField(blank=True, max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('dependente_01', models.CharField(blank=True, max_length=100)),
                ('dependente_02', models.CharField(blank=True, max_length=100)),
                ('dependente_03', models.CharField(blank=True, max_length=100)),
                ('dependente_04', models.CharField(blank=True, max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('orgao_emissor', models.CharField(max_length=100)),
                ('data_emissao', models.CharField(max_length=100)),
                ('passaporte', models.CharField(blank=True, max_length=100)),
                ('validade_passaporte', models.CharField(blank=True, max_length=100)),
                ('cr', models.CharField(blank=True, max_length=100)),
                ('validade_cr', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
