# Generated by Django 4.2 on 2023-04-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='paratleta',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=100),
        ),
    ]
