# Generated by Django 4.2 on 2023-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formUser', '0002_alter_cliente_paratleta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosPessoais',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_emissao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='orgao_emissor',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='passaporte',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='validade_cr',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='validade_passaporte',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
